name: $(Build.MajorNumber).$(Build.MinorNumber)$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - 'SFA.DAS.Elastic'

workspace:
    clean: all

pool:
  name: 'DAS - Continuous Integration'

variables:
  - group: "ESFA - SonarCloud"
  - name: sonarCloudProjectKey
    value: "SkillsFundingAgency_das-shared-packages"
  - name: BuildConfiguration
    value: 'Release'
  - name: Build.MajorNumber
    value: '2'
  - name: Build.MinorNumber
    value: '0'

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: "GitHub (SFA)"

steps:
- task: SonarCloudPrepare@1
  displayName: 'Prepare Sonarcloud analysis configuration'
  inputs:
    SonarCloud: "$(SonarCloudConnectionId)"
    organization: "$(SonarCloudOrganisationKey)"
    scannerMode: 'MSBuild'
    projectName: "$(Build.DefinitionName)"
    projectKey: "$(sonarCloudProjectKey)" 

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: SFA.DAS.Elastic/SFA.DAS.Elastic.sln

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: SFA.DAS.Elastic/SFA.DAS.Elastic.sln
    arguments: '--configuration $(BuildConfiguration) --no-restore'

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud analysis'
  
- task: SonarCloudPublish@1
  displayName: 'Publish results on build summary'
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: SFA.DAS.Elastic/SFA.DAS.Elastic.UnitTests/SFA.DAS.Elastic.UnitTests.csproj
    arguments: '--configuration $(BuildConfiguration) --no-build'

- template: azure-pipelines-templates/dependency-check.yml@das-platform-building-blocks

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: SFA.DAS.Elastic/SFA.DAS.Elastic/SFA.DAS.Elastic.csproj
    versioningScheme: byBuildNumber

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: SFA.DAS.Elastic/SFA.DAS.Elastic
    Contents: '**/*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'