name: $(Build.MajorNumber).$(Build.MinorNumber)$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - 'SFA.DAS.Elastic'

pr: none

workspace:
    clean: all

pool:
  name: 'DAS - Continuous Integration'

variables:
  BuildConfiguration: 'Release'
  Build.MajorNumber: '1'
  Build.MinorNumber: '0'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: SFA.DAS.Elastic/SFA.DAS.Elastic.sln

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: SFA.DAS.Elastic/SFA.DAS.Elastic/SFA.DAS.Elastic.csproj
    arguments: '/p:Configuration=$(BuildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: SFA.DAS.Elastic/SFA.DAS.Elastic.UnitTests/SFA.DAS.Elastic.UnitTests.csproj
    arguments: '--configuration $(buildConfiguration) --no-build'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: SFA.DAS.Elastic/SFA.DAS.Elastic/SFA.DAS.Elastic.csproj
    versioningScheme: byBuildNumber

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: SFA.DAS.Elastic/SFA.DAS.Elastic
    Contents: '**/*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'