trigger:
  batch: true
  branches:
    include:
      - "master"
  paths:
    include:
    - pipeline-templates
    - SFA.DAS.MA.Shared.UI

pr:
  autoCancel: true
  branches:
    include:
      - "master"
  paths:
    include:
    - pipeline-templates
    - SFA.DAS.MA.Shared.UI

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.64
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: ../pipeline-templates/job/code-build.yml
    parameters:
      WorkingDirectory: SFA.DAS.MA.Shared.UI
      DotNetFrameworkPackagesToPack: SFA.DAS.MA.Shared.UI/SFA.DAS.MA.Shared.UI/SFA.DAS.MA.Shared.UI.csproj
      SonarCloudProjectKey: SkillsFundingAgency_das-shared-packages_SFA.DAS.MA.Shared.UI
      SdkStyleFrameworkProjects: true
- template: azure-pipelines-templates/deploy/stage/nuget-publish.yml@das-platform-building-blocks
