name: $(Build.MajorNumber).$(Build.MinorNumber)$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - 'SFA.DAS.MA.Shared.UI'

workspace:
    clean: all

pool:
  name: 'Continuous Integration 02 - SSD - 160ACU'
  demands: 
  - msbuild
  - visualstudio

variables:
  - group: "ESFA - SonarCloud"
  - name: sonarCloudProjectKey
    value: "SkillsFundingAgency_das-shared-packages"
  - name: BuildConfiguration
    value: 'Release'
  - name: Build.MajorNumber
    value: '1'
  - name: Build.MinorNumber
    value: '1'
  - name: BuildPlatform
    value: 'any cpu'

steps:
- task: SonarCloudPrepare@1
  displayName: 'Prepare Sonarcloud analysis configuration'
  inputs:
    SonarCloud: "$(SonarCloudConnectionId)"
    organization: "$(SonarCloudOrganisationKey)"
    scannerMode: 'MSBuild'
    projectName: "$(Build.DefinitionName)"
    projectKey: "$(sonarCloudProjectKey)" 

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.3.0'
  inputs:
    versionSpec: 4.x

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: SFA.DAS.MA.Shared.UI/SFA.DAS.MA.Shared.UI.sln
    
- task: VSBuild@1
  displayName: 'VS Build'
  inputs:
    solution: SFA.DAS.MA.Shared.UI/SFA.DAS.MA.Shared.UI.sln
    vsVersion: 15.0
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)/publish"'
    platform: '$(BuildPlatform)'
    Configuration: '$(BuildConfiguration)'

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud analysis'
  
- task: SonarCloudPublish@1
  displayName: 'Publish results on build summary'
  inputs:
    pollingTimeoutSec: '300'     

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: SFA.DAS.MA.Shared.UI/SFA.DAS.MA.Shared.UI/SFA.DAS.MA.Shared.UI.csproj
    versioningScheme: byBuildNumber

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

