name: $(Build.MajorNumber).$(Build.MinorNumber)$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - 'SFA.DAS.MA.Shared.UI'

pr: none

workspace:
    clean: all

pool:
  name: 'Continuous Integration 02 - SSD - 160ACU'
  demands: 
  - msbuild
  - visualstudio

variables:
  BuildConfiguration: 'Release'
  Build.MajorNumber: '1'
  Build.MinorNumber: '1'
  BuildPlatform: 'any cpu'

steps:    
- task: VSBuild@1
  displayName: 'VSBuild restore'
  inputs:
    solution: SFA.DAS.MA.Shared.UI/SFA.DAS.MA.Shared.UI.sln
    vsVersion: 15.0
    msbuildArgs: '/t:restore'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    clean: true
    
- task: VSBuild@1
  displayName: 'VS Build'
  inputs:
    solution: SFA.DAS.MA.Shared.UI/SFA.DAS.MA.Shared.UI.sln
    vsVersion: 15.0
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)/publish"'
    platform: '$(BuildPlatform)'
    Configuration: '$(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: SFA.DAS.MA.Shared.UI/SFA.DAS.MA.Shared.UI/SFA.DAS.MA.Shared.UI.csproj
    versioningScheme: byBuildNumber

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

