name: $(Build.MajorNumber).$(Build.MinorNumber)$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - 'SFA.DAS.Authentication'

workspace:
    clean: all

pool:
  name: 'DAS - Continuous Integration'

variables:
  - group: "ESFA - SonarCloud"
  - name: sonarCloudProjectKey
    value: "SkillsFundingAgency_das-shared-packages"
  - name: BuildConfiguration
    value: 'Release'
  - name: Build.MajorNumber
    value: '1'
  - name: Build.MinorNumber
    value: '1'

steps:
- task: SonarCloudPrepare@1
  displayName: 'Prepare Sonarcloud analysis configuration'
  inputs:
    SonarCloud: "$(SonarCloudConnectionId)"
    organization: "$(SonarCloudOrganisationKey)"
    scannerMode: 'MSBuild'
    projectName: "$(Build.DefinitionName)"
    projectKey: "$(sonarCloudProjectKey)" 

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: SFA.DAS.Authentication/SFA.DAS.Authentication.sln

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: SFA.DAS.Authentication/SFA.DAS.Authentication.sln
    arguments: '/p:Configuration=$(BuildConfiguration)'

- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud analysis'
  
- task: SonarCloudPublish@1
  displayName: 'Publish results on build summary'
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: SFA.DAS.Authentication/SFA.DAS.Authentication/SFA.DAS.Authentication.csproj
    versioningScheme: byBuildNumber

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: SFA.DAS.Authentication/SFA.DAS.Authentication
    Contents: '**/*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

