trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - 'Logging'

pr: none

workspace:
    clean: all

name: $(Build.MajorNumber).$(Build.MinorNumber)$(Rev:.r)
pool:
  name: Continuous Integration 02 - SSD - 160ACU

variables:
  BuildConfiguration: 'Release'
  Build.MajorNumber: '1'
  Build.MinorNumber: '1'

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: "GitHub (SFA)"

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: Logging/SFA.DAS.Logging/SFA.DAS.Logging.sln

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: Logging/SFA.DAS.Logging/SFA.DAS.Logging.sln
    arguments: '/p:Configuration=$(BuildConfiguration)'

- template: azure-pipelines-templates/dependency-check.yml@das-platform-building-blocks

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: Logging/SFA.DAS.Logging/SFA.DAS.Logging.sln
    versioningScheme: byBuildNumber

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: Logging/SFA.DAS.Logging/SFA.DAS.Logging
    Contents: '**/*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
