trigger:
  batch: true
  branches:
    include:
      - "master"
  paths:
    include:
    - pipeline-templates
    - SFA.DAS.Authentication/SFA.DAS.Authentication.Extensions

pr:
  autoCancel: true
  branches:
    include:
      - "master"
  paths:
    include:
    - pipeline-templates
    - SFA.DAS.Authentication/SFA.DAS.Authentication.Extensions

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/1.0.2
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: ../../pipeline-templates/job/code-build.yml
    parameters:
      WorkingDirectory: SFA.DAS.Authentication/SFA.DAS.Authentication.Extensions
      DotNetFrameworkPackagesToPack: >
        SFA.DAS.Authentication/SFA.DAS.Authentication.Extensions/SFA.DAS.Authentication.Extensions/SFA.DAS.Authentication.Extensions.csproj;
        SFA.DAS.Authentication/SFA.DAS.Authentication.Extensions/SFA.DAS.Authentication.Extensions.Legacy/SFA.DAS.Authentication.Extensions.Legacy.csproj;
      SonarCloudProjectKey: SkillsFundingAgency_das-shared-packages_SFA.DAS.Authentication.Extensions
      SdkStyleFrameworkProjects: true
- template: azure-pipelines-templates/deploy/stage/nuget-publish.yml@das-platform-building-blocks