trigger:
  batch: true
  branches:
    include:
      - "master"
  paths:
    include:
    - pipeline-templates
    - SFA.DAS.GovUK.Auth

pr:
  autoCancel: true
  branches:
    include:
      - "master"
  paths:
    include:
    - pipeline-templates
    - SFA.DAS.GovUK.Auth

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/3.0.10
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: ../pipeline-templates/job/code-build.yml
    parameters:
      WorkingDirectory: SFA.DAS.GovUK.Auth
      DotNetStandardPackagesToPack: SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.Auth/SFA.DAS.GovUK.Auth.csproj
      SonarCloudProjectKey: SkillsFundingAgency_das-shared-packages_SFA.DAS.GovUK.Auth
- template: azure-pipelines-templates/deploy/stage/nuget-publish.yml@das-platform-building-blocks
