trigger:
  batch: true
  branches:
    include:
      - "master"
  paths:
    include:
    - pipeline-templates
    - Configuration

pr:
  autoCancel: true
  branches:
    include:
      - "master"
  paths:
    include:
    - pipeline-templates
    - Configuration

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.2.2
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: ../pipeline-templates/job/code-build.yml
    parameters:
      WorkingDirectory: Configuration
      DotNetStandardPackagesToPack: >
        Configuration/SFA.DAS.Configuration/SFA.DAS.Configuration.csproj;
        Configuration/SFA.DAS.Configuration.AzureTableStorage/SFA.DAS.Configuration.AzureTableStorage.csproj
      SonarCloudProjectKey: SkillsFundingAgency_das-shared-packages_Configuration
- template: azure-pipelines-templates/deploy/stage/nuget-publish.yml@das-platform-building-blocks
