trigger:
  batch: true
  branches:
    include:
      - "master"
  paths:
    include:
    - pipeline-templates
    - SFA.DAS.Testing

pr:
  autoCancel: true
  branches:
    include:
      - "master"
  paths:
    include:
    - pipeline-templates
    - SFA.DAS.Testing

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.2.2
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: ../pipeline-templates/job/code-build.yml
    parameters:
      WorkingDirectory: SFA.DAS.Testing
      DotNetStandardPackagesToPack: >
        SFA.DAS.Testing/SFA.DAS.Testing/SFA.DAS.Testing.csproj;
        SFA.DAS.Testing/SFA.DAS.Testing.AutoFixture/SFA.DAS.Testing.AutoFixture.csproj;
        SFA.DAS.Testing/SFA.DAS.Testing.AzureStorageEmulator/SFA.DAS.Testing.AzureStorageEmulator.csproj;
        SFA.DAS.Testing/SFA.DAS.Testing.PackageScanning/SFA.DAS.Testing.PackageScanning.csproj
      SonarCloudProjectKey: SkillsFundingAgency_das-shared-packages_SFA.DAS.Testing
- template: azure-pipelines-templates/deploy/stage/nuget-publish.yml@das-platform-building-blocks
