using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using OpenTelemetry;

namespace SFA.DAS.Telemetry.NotFoundResponseProcessor;

public class NotFoundAsSuccessResponseProcessor(IHttpContextAccessor _httpContextAccessor) : BaseProcessor<Activity>
{
    public override void OnEnd(Activity activity)
    {
        if (activity.Kind == ActivityKind.Server)
        {
            var httpContext = _httpContextAccessor.HttpContext;

            if (httpContext?.Response.StatusCode == 404)
            {
                var matchedEndpoint = httpContext.GetEndpoint();

                // ONLY make 404s success when generated by application code:
                if (matchedEndpoint != null)
                {
                    MarkTelemetryAsSuccess(activity);
                }
            }
        }
    }
    private static void MarkTelemetryAsSuccess(Activity activity)
    {
        // Clear the error status
        activity.SetStatus(ActivityStatusCode.Unset);

        // Wipe standard OpenTelemetry error indicators
        activity.SetTag("error.type", null);
        activity.SetTag("otel.status_code", "OK");
    }
}
